### ISSUE TITLE
lots of warnings by default because of $

### ISSUE THREAD

**Issue by incanus** [nfarina/calloutview#78]
The dolla dolla introduced in https://github.com/nfarina/calloutview/issues/72 causes problems with Xcode's default warnings. This is triggered by `-Wdollar-in-identifier-extension`. 

/cc @1ec5

![screen shot 2015-03-24 at 11 10 33 am](https://cloud.githubusercontent.com/assets/17722/6809308/b15aff0c-d216-11e4-8c88-091b0392df6c.png)

**Comment by nfarina** [comment]
Oh snap ... OK will pick something else!

**Comment by incanus** [comment]
You could also maybe inline pragma-ignore the warning?

**Comment by 1ec5** [comment]
[Missed one](https://github.com/nfarina/calloutview/blob/14a8d87b77e7280accc0919854df2b4956eeaefa/SMCalloutView.m#L778).

**Comment by nfarina** [comment]
Oh snap, good catch. Fixing...
