### ISSUE TITLE
Using SMCalloutView wit Mapbox

### ISSUE THREAD

**Issue by blazejchwiecko** [nfarina/calloutview#88]
Hello there,

I try to implement SMCalloutView to my project where I'm using Mapbox SDK 1.6.1, everything works great as long as I don't add SMCalloutView h. and m., after that Xcode can't build my app, because of linker errors. Is there solution for it?

**Comment by nfarina** [comment]
Hello, I believe Mapbox embeds `SMCalloutView` directly for you - you might be able to include `SMCalloutView.h` directly from the Mapbox SDK yourself, or you can simply copy `SMCalloutView.h` by itself and don't copy the `.m` file (because that will cause duplicate symbols).

**Comment by blazejchwiecko** [comment]
Thanks! Now, works like a charm. :)

**Comment by nfarina** [comment]
Excellent!
