### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by ipedro** [nfarina/calloutview#90]
First of all, great lib!

Converting my project from the native callout I realised there's a performance hit when scrolling around the map. Since the callout doesn't support live updates, have you ever considered showing a flattened UIImage copy instead? (or something like it)

Did a quick test here and saw a big improvement.

**Comment by nfarina** [comment]
Hm; the performance should be nearly identical to the native callout since it's built the exact same way... Are you seeing different performance characteristics for callouts containing the exact same content?

**Comment by nfarina** [comment]
Also thanks :) I would consider image flattening to be a last resort since it feels "unexpected" but maybe we can think of some other sort of caching
